function figureHandle = createPupilReviewFigure(result, cfg)
%CREATEPUPILREVIEWFIGURE Export the review-only S01 pupil overlay.

figureHandle = figure('Visible', cfg.visualisation.Visible, 'Color', 'w', ...
    'Position', [80, 100, 1450, 650]);
layout = tiledlayout(figureHandle, 1, 2, 'TileSpacing', 'compact', ...
    'Padding', 'loose');
[fullImage, ~] = readImageWithExifOrientation(char(result.SourcePath));
plotPupilReviewOverlay(nexttile(layout), fullImage, ...
    result.Preprocessing, "full");
title(sprintf('Full image | pupil %s', ...
    result.Preprocessing.Pupil.DetectionStatus), 'Interpreter', 'none');
plotPupilReviewOverlay(nexttile(layout), result.Preprocessing.RGB, ...
    result.Preprocessing, "crop");
if result.Preprocessing.Pupil.IsValid
    subtitle = sprintf(['Review-only circle | sensor-equivalent diameter %.3f mm | ' ...
        'sensor offset %.3f mm | score %.3f'], ...
        result.Preprocessing.Pupil.EquivalentDiameterSensorMm, ...
        result.Preprocessing.Pupil.OffsetMagnitudeSensorMm, ...
        result.Preprocessing.Pupil.Score);
else
    subtitle = "Not accepted: " + result.Preprocessing.Pupil.FailureReason;
end
title(layout, ["S01 Placido-style pupil review | " + result.CaseId; subtitle], ...
    'Interpreter', 'none', 'FontWeight', 'bold');
end
