function figureHandle = createEigenRatioAxesFigure(result, cfg)
%CREATEEIGENRATIOAXESFIGURE Export complete-mire principal-axis plots.

figureHandle = figure('Visible', cfg.visualisation.Visible, 'Color', 'w', ...
    'Position', [200, 80, 950, 760]);
layout = tiledlayout(figureHandle, 1, 1, 'TileSpacing', 'compact', ...
    'Padding', 'loose');
[variant, displayName] = selectEigenRatioVariant(result, cfg);
plotCompleteMireAxes(nexttile(layout), variant, ...
    result.Preprocessing, cfg, displayName + ' complete-mire axes');
title(layout, ["S07 complete-mire harmonic axes | " + result.CaseId; ...
    displayName + " " + variant.Segmentation.MethodActual + ...
    " | sensor-plane descriptors; not clinical axes"], ...
    'Interpreter', 'none', 'FontWeight', 'bold');
end
