function metricsTable = evaluateSyntheticSegmentationDataset(cfg, outputCsv)
%EVALUATESYNTHETICSEGMENTATIONDATASET Score masks and localized mire labels.
%   Compares SmartKC, the robust classical fallback, and the validated U-Net
%   when installed. Binary mask metrics share one exact synthetic truth.
%   Mire-index metrics score localized radial candidates against true radii.

arguments
    cfg struct
    outputCsv (1,1) string = ""
end

manifestPath = fullfile(cfg.paths.Synthetic, 'manifest.csv');
manifest = readtable(manifestPath, 'TextType', 'string');
methodsPerCase = 3;
empty = emptyRecord();
records = repmat(empty, height(manifest) * methodsPerCase, 1);
recordIndex = 0;

for caseIndex = 1:height(manifest)
    imagePath = fullfile(cfg.paths.Synthetic, manifest.ImageFile(caseIndex));
    truthPath = fullfile(cfg.paths.Synthetic, ...
        manifest.GroundTruthFile(caseIndex));
    loaded = load(truthPath, 'truth');
    truth = loaded.truth;
    caseCfg = cfg;
    caseCfg.preprocessing.PupilRadiusFraction = [0.018, 0.04];
    caseCfg.localization.InnerRadiusPx = 4;
    pre = preprocessPlacidoImage(char(imagePath), caseCfg);
    croppedTruth = cropSyntheticTruthToPreprocessed(truth, pre);
    [xx, yy] = meshgrid(1:size(pre.Gray, 2), 1:size(pre.Gray, 1));
    radius = hypot(xx-pre.CenterPx(1), yy-pre.CenterPx(2));
    evaluationMask = radius >= caseCfg.localization.InnerRadiusPx & ...
        radius <= pre.AnalysisRadiusPx;

    smartKCSegmentation = segmentMiresClassical(pre, caseCfg, "smartkc");
    [smartKCCandidates, ~] = extractMireCandidates( ...
        pre, smartKCSegmentation, caseCfg);
    recordIndex = recordIndex + 1;
    records(recordIndex) = scoreMethod(manifest.ScenarioName(caseIndex), ...
        "SmartKC", smartKCSegmentation.MethodActual, smartKCSegmentation, ...
        smartKCCandidates, croppedTruth, truth, evaluationMask, caseCfg);

    fallbackSegmentation = segmentMiresClassical(pre, caseCfg, "robust");
    [fallbackRawCandidates, ~] = extractMireCandidates( ...
        pre, fallbackSegmentation, caseCfg);
    fallbackCandidates = correctMireLabelsGraph( ...
        fallbackRawCandidates, pre.CenterPx, caseCfg);
    recordIndex = recordIndex + 1;
    records(recordIndex) = scoreMethod(manifest.ScenarioName(caseIndex), ...
        "SmartKC++ fallback", "robust-classical-fallback", ...
        fallbackSegmentation, fallbackCandidates, croppedTruth, truth, ...
        evaluationMask, caseCfg);

    recordIndex = recordIndex + 1;
    records(recordIndex).ScenarioName = manifest.ScenarioName(caseIndex);
    records(recordIndex).Method = "SmartKC++ official U-Net";
    strictCfg = caseCfg;
    strictCfg.segmentation.AllowClassicalFallback = false;
    try
        unetSegmentation = segmentMiresSmartKCPlus(pre, strictCfg);
        [unetRawCandidates, ~] = extractMireCandidates( ...
            pre, unetSegmentation, strictCfg);
        unetCandidates = correctMireLabelsGraph( ...
            unetRawCandidates, pre.CenterPx, strictCfg);
        records(recordIndex) = scoreMethod( ...
            manifest.ScenarioName(caseIndex), ...
            "SmartKC++ official U-Net", unetSegmentation.MethodActual, ...
            unetSegmentation, unetCandidates, croppedTruth, truth, ...
            evaluationMask, strictCfg);
    catch exception
        records(recordIndex).MethodActual = "unavailable";
        records(recordIndex).Status = "UNAVAILABLE";
        records(recordIndex).ErrorMessage = string(exception.identifier) + ...
            ": " + string(exception.message);
    end
end

metricsTable = struct2table(records);
if strlength(outputCsv) > 0
    ensureFolder(fileparts(char(outputCsv)));
    writetable(metricsTable, char(outputCsv));
end
end

function record = scoreMethod(scenarioName, method, methodActual, ...
        segmentation, candidates, croppedTruth, truth, evaluationMask, cfg)
binary = computeBinarySegmentationMetrics(segmentation.Mask, ...
    croppedTruth.BinaryMireMask, evaluationMask);
localization = evaluateMireLocalizationAgainstTruth(candidates, truth, ...
    cfg.placido.MaximumMires, 3);
record = emptyRecord();
record.ScenarioName = scenarioName;
record.Method = method;
record.MethodActual = string(methodActual);
record.Status = "COMPLETED";
record.Dice = binary.Dice;
record.IoU = binary.IoU;
record.Precision = binary.Precision;
record.Recall = binary.Recall;
record.Specificity = binary.Specificity;
record.PredictedForegroundFraction = binary.PredictedForegroundFraction;
record.TruthForegroundFraction = binary.TruthForegroundFraction;
record.CandidateCount = localization.CandidateCount;
record.MatchedCandidateCount = localization.MatchedCandidateCount;
record.MatchedCandidateFraction = localization.MatchedCandidateFraction;
record.PhysicalMireIndexAccuracy = localization.PhysicalMireIndexAccuracy;
record.MeanAbsolutePhysicalMireIndexError = ...
    localization.MeanAbsolutePhysicalMireIndexError;
record.DominantMireIndexOffset = localization.DominantMireIndexOffset;
record.OffsetAlignedMireIndexAccuracy = ...
    localization.OffsetAlignedMireIndexAccuracy;
record.MeanAbsoluteAlignedMireIndexError = ...
    localization.MeanAbsoluteAlignedMireIndexError;
record.MedianRadialErrorPx = localization.MedianRadialErrorPx;
record.RadialMatchTolerancePx = localization.RadialMatchTolerancePx;
end

function record = emptyRecord()
record = struct( ...
    'ScenarioName', "", ...
    'Method', "", ...
    'MethodActual', "", ...
    'Status', "NOT_RUN", ...
    'Dice', NaN, ...
    'IoU', NaN, ...
    'Precision', NaN, ...
    'Recall', NaN, ...
    'Specificity', NaN, ...
    'PredictedForegroundFraction', NaN, ...
    'TruthForegroundFraction', NaN, ...
    'CandidateCount', NaN, ...
    'MatchedCandidateCount', NaN, ...
    'MatchedCandidateFraction', NaN, ...
    'PhysicalMireIndexAccuracy', NaN, ...
    'MeanAbsolutePhysicalMireIndexError', NaN, ...
    'DominantMireIndexOffset', NaN, ...
    'OffsetAlignedMireIndexAccuracy', NaN, ...
    'MeanAbsoluteAlignedMireIndexError', NaN, ...
    'MedianRadialErrorPx', NaN, ...
    'RadialMatchTolerancePx', NaN, ...
    'ErrorMessage', "");
end
