function output = pupilForCsv(pre, cfg)
%PUPILFORCSV Create one review-only pupil row with millimetre spatial fields.

pupil = pre.Pupil;
calibrationStatus = "UNCALIBRATED_REFERENCE_GEOMETRY";
if cfg.calibration.IsDeviceSpecific
    calibrationStatus = "DEVICE_PROFILE_SET_REQUIRES_VALIDATION";
end
output = table(pre.CaseId, pupil.Method, pupil.SourceFrameMode, ...
    pupil.DetectionStatus, pupil.IsValid, pupil.Metric, pupil.Score, ...
    pupil.CenterRelativeToPlacidoSensorMm(1), ...
    pupil.CenterRelativeToPlacidoSensorMm(2), ...
    pupil.OffsetMagnitudeSensorMm, pupil.DiameterXSensorMm, ...
    pupil.DiameterYSensorMm, pupil.EquivalentDiameterSensorMm, ...
    pupil.SpatialUnit, pupil.CoordinateFrame, calibrationStatus, ...
    string(pupil.FailureReason), string(pupil.Warning), ...
    'VariableNames', {'CaseId','Method','SourceFrameMode','DetectionStatus', ...
    'IsValid','HoughMetric','CombinedScore', ...
    'CenterXRelativeToPlacidoSensorMm', ...
    'CenterYRelativeToPlacidoSensorMm','CenterOffsetMagnitudeSensorMm', ...
    'SensorDiameterXmm','SensorDiameterYmm','SensorEquivalentDiameterMm', ...
    'SpatialUnit','CoordinateFrame', ...
    'CalibrationStatus','FailureReason','Warning'});
end
