function savePipelineOutputs(result, outputFolder, cfg)
%SAVEPIPELINEOUTPUTS Write MAT, CSV, image and review-figure artifacts.

ensureFolder(outputFolder);
imwrite(im2uint8(result.Preprocessing.RGB), ...
    fullfile(outputFolder, 'S01_crop.png'));
imwrite(im2uint8(result.Preprocessing.NormalizedGray), ...
    fullfile(outputFolder, 'S01_normalized.png'));
writetable(pupilForCsv(result.Preprocessing, cfg), ...
    fullfile(outputFolder, 'S01_pupil.csv'));
pupilFigure = createPupilReviewFigure(result, cfg);
exportgraphics(pupilFigure, fullfile(outputFolder, 'S01_pupil_review.png'), ...
    'Resolution', cfg.visualisation.SaveResolutionDpi);
close(pupilFigure);
imwrite(result.SmartKC.Segmentation.Mask, ...
    fullfile(outputFolder, 'S02_skc_mask.png'));
imwrite(result.SmartKCPP.Segmentation.Mask, ...
    fullfile(outputFolder, 'S02_skcpp_mask.png'));

smartKCCsv = mirePointsForCsv(result.SmartKC.Candidates, ...
    result.Preprocessing, cfg);
smartKCPPCsv = mirePointsForCsv(result.SmartKCPP.Candidates, ...
    result.Preprocessing, cfg);
writetable(smartKCCsv, fullfile(outputFolder, 'S03_skc_mires.csv'));
writetable(smartKCPPCsv, fullfile(outputFolder, 'S03_skcpp_mires.csv'));
writeMireViewerMetadata(result, outputFolder, cfg);
if result.SmartKC.Status == "COMPLETED"
    writetable(result.SmartKC.Reconstruction.Points, ...
        fullfile(outputFolder, 'S04_skc_surface.csv'));
end
if result.SmartKCPP.Status == "COMPLETED"
    writetable(result.SmartKCPP.Reconstruction.Points, ...
        fullfile(outputFolder, 'S05_skcpp_surface.csv'));
end

summary = buildSummary(result);
writetable(summary, fullfile(outputFolder, 'S06_summary.csv'));
save(fullfile(outputFolder, 'S06_result.mat'), ...
    'result', '-v7.3');

figureHandle = createPipelineReviewFigure(result, cfg);
reviewPath = fullfile(outputFolder, 'S06_review.png');
exportgraphics(figureHandle, reviewPath, ...
    'Resolution', cfg.visualisation.SaveResolutionDpi);
close(figureHandle);

if cfg.eigenRatio.Enabled
    [eigenVariant, ~] = selectEigenRatioVariant(result, cfg);
    eigenMetrics = eigenVariant.EigenRatio.Metrics;
    segmentationMethod = repmat( ...
        string(eigenVariant.Segmentation.MethodActual), height(eigenMetrics), 1);
    eigenMetrics = addvars(eigenMetrics, segmentationMethod, ...
        'After', 'Pipeline', 'NewVariableNames', 'SegmentationMethod');
    writetable(eigenMetrics, fullfile(outputFolder, 'S07_eigen_ratio.csv'));
    eigenFigure = createEigenRatioFigure(result, cfg);
    exportgraphics(eigenFigure, fullfile(outputFolder, ...
        'S07_eigen_ratio.png'), ...
        'Resolution', cfg.visualisation.SaveResolutionDpi);
    close(eigenFigure);
    axesFigure = createEigenRatioAxesFigure(result, cfg);
    exportgraphics(axesFigure, fullfile(outputFolder, 'S07_axes.png'), ...
        'Resolution', cfg.visualisation.SaveResolutionDpi);
    close(axesFigure);
end
end

function summary = buildSummary(result)
names = ["SmartKC"; "SmartKC++"];
variants = {result.SmartKC; result.SmartKCPP};
status = strings(2, 1);
segmentationMethod = strings(2, 1);
simKSteepD = nan(2, 1);
simKFlatD = nan(2, 1);
cylinderD = nan(2, 1);
steepAxisDeg = nan(2, 1);
medianMiresPerAngle = nan(2, 1);
reconstructedMeridians = nan(2, 1);
surfaceFitRMSEum = nan(2, 1);
acceptedForResearchReview = false(2, 1);
mireIdentityAnchorValidated = false(2, 1);
mireIdentityAnchorStatus = strings(2, 1);
errorMessage = strings(2, 1);
for i = 1:2
    value = variants{i};
    status(i) = value.Status;
    segmentationMethod(i) = value.Segmentation.MethodActual;
    errorMessage(i) = value.ErrorMessage;
    if value.Status ~= "COMPLETED"
        continue
    end
    simKSteepD(i) = value.Metrics.SimKSteepD;
    simKFlatD(i) = value.Metrics.SimKFlatD;
    cylinderD(i) = value.Metrics.CylinderD;
    steepAxisDeg(i) = value.Metrics.SimKSteepAxisDeg;
    medianMiresPerAngle(i) = value.Quality.MedianMiresPerAngle;
    reconstructedMeridians(i) = value.Quality.ReconstructedMeridians;
    surfaceFitRMSEum(i) = value.Quality.SurfaceFitRMSEum;
    acceptedForResearchReview(i) = value.Quality.IsAcceptedForResearchReview;
    mireIdentityAnchorValidated(i) = ...
        value.Quality.MireIdentityAnchorValidated;
    mireIdentityAnchorStatus(i) = value.Quality.MireIdentityAnchorStatus;
end
calibrationStatus = repmat("UNCALIBRATED_RESEARCH_OUTPUT", 2, 1);
if result.Calibration.IsDeviceSpecific
    calibrationStatus(:) = "DEVICE_PROFILE_SET_REQUIRES_VALIDATION";
end
pupilDetectionStatus = repmat( ...
    string(result.Preprocessing.Pupil.DetectionStatus), 2, 1);
pupilScore = repmat(result.Preprocessing.Pupil.Score, 2, 1);
pupilCenterOffsetSensorMm = repmat( ...
    result.Preprocessing.Pupil.OffsetMagnitudeSensorMm, 2, 1);
pupilEquivalentSensorDiameterMm = repmat( ...
    result.Preprocessing.Pupil.EquivalentDiameterSensorMm, 2, 1);
inputResizeScale = repmat(result.Preprocessing.InputResizeScale, 2, 1);
sourceImageHeightPx = repmat( ...
    result.Preprocessing.SourceOriginalSize(1), 2, 1);
sourceImageWidthPx = repmat( ...
    result.Preprocessing.SourceOriginalSize(2), 2, 1);
processingImageHeightPx = repmat(result.Preprocessing.OriginalSize(1), 2, 1);
processingImageWidthPx = repmat(result.Preprocessing.OriginalSize(2), 2, 1);
exifOrientation = repmat(result.Preprocessing.ExifOrientation, 2, 1);
exifOrientationApplied = repmat( ...
    result.Preprocessing.ExifOrientationApplied, 2, 1);
processingSensorWidthMm = repmat( ...
    result.Preprocessing.ProcessingSensorSizeMm(1), 2, 1);
processingSensorHeightMm = repmat( ...
    result.Preprocessing.ProcessingSensorSizeMm(2), 2, 1);
summary = table(names, status, segmentationMethod, simKSteepD, simKFlatD, ...
    cylinderD, steepAxisDeg, medianMiresPerAngle, reconstructedMeridians, ...
    surfaceFitRMSEum, acceptedForResearchReview, ...
    mireIdentityAnchorValidated, mireIdentityAnchorStatus, ...
    pupilDetectionStatus, ...
    pupilScore, pupilCenterOffsetSensorMm, pupilEquivalentSensorDiameterMm, ...
    inputResizeScale, sourceImageHeightPx, sourceImageWidthPx, ...
    processingImageHeightPx, processingImageWidthPx, ...
    exifOrientation, exifOrientationApplied, processingSensorWidthMm, ...
    processingSensorHeightMm, ...
    calibrationStatus, errorMessage, ...
    'VariableNames', {'Pipeline','Status','SegmentationMethod','SimKSteepD', ...
    'SimKFlatD','CylinderD','SteepAxisDeg','MedianMiresPerAngle', ...
    'ReconstructedMeridians','SurfaceFitRMSEum','AcceptedForResearchReview', ...
    'MireIdentityAnchorValidated','MireIdentityAnchorStatus', ...
    'PupilDetectionStatus','PupilScore','PupilCenterOffsetSensorMm', ...
    'PupilEquivalentSensorDiameterMm','InputResizeScale', ...
    'SourceImageHeightPx','SourceImageWidthPx','ProcessingImageHeightPx', ...
    'ProcessingImageWidthPx','ExifOrientation','ExifOrientationApplied', ...
    'ProcessingSensorWidthMm','ProcessingSensorHeightMm', ...
    'CalibrationStatus','ErrorMessage'});
end
